"""
Event-sourced session service: append-only session log, in-memory store, and
derived LLM message history.
1:1 aligned with official `@deepseek-ai/dsh-session`.
Compatible with Python 3.8.10 and Windows 7 SP1.
"""

from dsh.core.session.chunk_rows import (
    decode_storage_record,
    decodeStorageRecord,
    pack_chunk_runs,
    packChunkRuns,
)
from dsh.core.session.invariant import SessionInvariantPlugin
from dsh.core.session.json import (
    is_json_value,
    isJsonValue,
    snapshot_json_value,
    snapshotJsonValue,
)
from dsh.core.session.known_event_types import KNOWN_SESSION_EVENT_TYPES
from dsh.core.session.preparation import SessionPreparation
from dsh.core.session.repair import (
    TOOL_NOT_STARTED,
    TOOL_OUTCOME_UNKNOWN,
    interrupted_turn_closers,
    interruptedTurnClosers,
)
from dsh.core.session.request_header import (
    canonical_header,
    canonicalHeader,
    fold_request_header,
    foldRequestHeader,
    header_equals,
    headerEquals,
)
from dsh.core.session.seq_ranges import (
    decode_seq_ranges,
    decodeSeqRanges,
    encode_seq_ranges,
    encodeSeqRanges,
)
from dsh.core.session.session import (
    Session,
    SessionPlugin,
    SessionService,
    SessionStore,
)
from dsh.core.session.surface import (
    SURFACE_EVENT_TYPES,
    SurfaceFoldReplacement,
    SurfaceFoldResult,
    SurfaceManager,
    SurfacePlan,
    derive_event_message,
    deriveEventMessage,
    fold_surface,
    foldSurface,
    is_append_surface_event,
    is_replacement_surface_event,
    is_surface_eligible_type,
    is_surface_event,
    isAppendSurfaceEvent,
    isReplacementSurfaceEvent,
    isSurfaceEligibleType,
    isSurfaceEvent,
    tool_pairing_balanced_after,
    tool_pairing_balanced_before,
)
from dsh.core.session.types import (
    ALLOWED_ADAPTER_DEFAULTS,
    ALLOWED_ENVELOPE_KEYS,
    SESSION_FORMAT_VERSION,
    SessionEvent,
    SessionForkError,
    SessionHeader,
    SessionId,
    adopt_session_event,
    adoptSessionEvent,
    assert_adapter_defaults,
    assert_current_llm_shape,
    assert_message_event_shape,
    assert_session_event_envelope,
    assert_supported_request_header,
    snapshot_session_event,
    snapshot_session_header,
    snapshotSessionEvent,
    validate_restored_session_header,
    validate_session_header,
)
from dsh.llm.message import (
    create_assistant_message,
    create_message,
    create_tool_result_message,
    create_user_message,
    createAssistantMessage,
    createMessage,
    createToolResultMessage,
    createUserMessage,
    freeze_message,
    freezeMessage,
)

__all__ = [
    "SESSION_FORMAT_VERSION",
    "SessionId",
    "SessionEvent",
    "ALLOWED_ENVELOPE_KEYS",
    "ALLOWED_ADAPTER_DEFAULTS",
    "SessionForkError",
    "SessionHeader",
    "validate_session_header",
    "validate_restored_session_header",
    "snapshot_session_header",
    "adopt_session_event",
    "adoptSessionEvent",
    "snapshot_session_event",
    "snapshotSessionEvent",
    "assert_session_event_envelope",
    "assert_current_llm_shape",
    "assert_message_event_shape",
    "assert_adapter_defaults",
    "assert_supported_request_header",
    "is_json_value",
    "isJsonValue",
    "snapshot_json_value",
    "snapshotJsonValue",
    "interrupted_turn_closers",
    "interruptedTurnClosers",
    "TOOL_NOT_STARTED",
    "TOOL_OUTCOME_UNKNOWN",
    "canonical_header",
    "canonicalHeader",
    "header_equals",
    "headerEquals",
    "fold_request_header",
    "foldRequestHeader",
    "encode_seq_ranges",
    "encodeSeqRanges",
    "decode_seq_ranges",
    "decodeSeqRanges",
    "pack_chunk_runs",
    "packChunkRuns",
    "decode_storage_record",
    "decodeStorageRecord",
    "KNOWN_SESSION_EVENT_TYPES",
    "SessionPreparation",
    "SURFACE_EVENT_TYPES",
    "SurfaceFoldReplacement",
    "SurfaceFoldResult",
    "SurfacePlan",
    "SurfaceManager",
    "derive_event_message",
    "deriveEventMessage",
    "fold_surface",
    "foldSurface",
    "is_surface_eligible_type",
    "isSurfaceEligibleType",
    "is_surface_event",
    "isSurfaceEvent",
    "is_append_surface_event",
    "isAppendSurfaceEvent",
    "is_replacement_surface_event",
    "isReplacementSurfaceEvent",
    "tool_pairing_balanced_after",
    "tool_pairing_balanced_before",
    "Session",
    "SessionStore",
    "SessionService",
    "SessionPlugin",
    "SessionInvariantPlugin",
    "create_user_message",
    "createUserMessage",
    "create_assistant_message",
    "createAssistantMessage",
    "create_tool_result_message",
    "createToolResultMessage",
    "create_message",
    "createMessage",
    "freeze_message",
    "freezeMessage",
]
