import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from scripts.canonical_llm_values import observation_digest as value_digest
from scripts.runtime_context_oracle import SOURCE_COMMIT, source_pin, validate_executable
from scripts.import_paths import resolve_import_path

GROUPS = ('retry', 'auxiliary', 'failure', 'boundary', 'iterator')
GROUP_MODULES = {'retry': ['dsh/__init__.py',
           'dsh/cordis/__init__.py',
           'dsh/cordis/awaiting.py',
           'dsh/cordis/context.py',
           'dsh/cordis/environment.py',
           'dsh/cordis/errors.py',
           'dsh/cordis/events.py',
           'dsh/cordis/fiber.py',
           'dsh/cordis/file_lock.py',
           'dsh/cordis/hmr.py',
           'dsh/cordis/include.py',
           'dsh/cordis/json_text.py',
           'dsh/cordis/loader.py',
           'dsh/cordis/logger.py',
           'dsh/cordis/plugin.py',
           'dsh/cordis/profile.py',
           'dsh/cordis/reflect.py',
           'dsh/cordis/registry.py',
           'dsh/cordis/schema.py',
           'dsh/cordis/service.py',
           'dsh/cordis/timer.py',
           'dsh/cordis/utils.py',
           'dsh/core/__init__.py',
           'dsh/core/abort.py',
           'dsh/core/agent.py',
           'dsh/core/agent_default_model_invariant.py',
           'dsh/core/agent_factory.py',
           'dsh/core/agent_loop.py',
           'dsh/core/agent_loop_settings.py',
           'dsh/core/cancellation.py',
           'dsh/core/configured_agents.py',
           'dsh/core/consumed_work.py',
           'dsh/core/inbox.py',
           'dsh/core/json_schema.py',
           'dsh/core/model_selection.py',
           'dsh/core/runtime_context.py',
           'dsh/core/scope.py',
           'dsh/core/session/__init__.py',
           'dsh/core/session/chunk_rows.py',
           'dsh/core/session/invariant.py',
           'dsh/core/session/json.py',
           'dsh/core/session/known_event_types.py',
           'dsh/core/session/preparation.py',
           'dsh/core/session/repair.py',
           'dsh/core/session/request_header.py',
           'dsh/core/session/seq_ranges.py',
           'dsh/core/session/session.py',
           'dsh/core/session/surface.py',
           'dsh/core/session/types.py',
           'dsh/core/surface.py',
           'dsh/core/system_prompt/__init__.py',
           'dsh/core/system_prompt/invariant.py',
           'dsh/core/system_prompt/layer.py',
           'dsh/core/system_prompt/service.py',
           'dsh/core/system_prompt/types.py',
           'dsh/core/tool_calls.py',
           'dsh/core/tools.py',
           'dsh/credentials/__init__.py',
           'dsh/credentials/authorization.py',
           'dsh/credentials/credentials.py',
           'dsh/credentials/credentials_local.py',
           'dsh/credentials/invariant.py',
           'dsh/credentials/types.py',
           'dsh/diagnostics/__init__.py',
           'dsh/diagnostics/invariants.py',
           'dsh/identity/__init__.py',
           'dsh/identity/anonymous_user_id.py',
           'dsh/identity/invariant.py',
           'dsh/identity/user_identity.py',
           'dsh/llm/adapter_failure.py',
           'dsh/llm/agent_request.py',
           'dsh/llm/attribution.py',
           'dsh/llm/call_config.py',
           'dsh/llm/deepseek_config.py',
           'dsh/llm/deepseek_schema.py',
           'dsh/llm/deepseek_wire.py',
           'dsh/llm/error.py',
           'dsh/llm/http_stream.py',
           'dsh/llm/image_content.py',
           'dsh/llm/llm_deepseek.py',
           'dsh/llm/llm_retry.py',
           'dsh/llm/llm_service.py',
           'dsh/llm/model_info.py',
           'dsh/llm/message.py',
           'dsh/llm/provider_errors.py',
           'dsh/llm/retry_policy.py',
           'dsh/llm/retry_schema.py',
           'dsh/llm/stream_bridge.py',
           'dsh/session/__init__.py',
           'dsh/session/checkpoint_policy.py',
           'dsh/session/checkpoint_policy_invariant.py',
           'dsh/session/durable_publish.py',
           'dsh/session/file_io.py',
           'dsh/session/file_revision.py',
           'dsh/session/icu_collation.py',
           'dsh/session/jsonl_format.py',
           'dsh/session/jsonl_store.py',
           'dsh/session/jsonl_zstd.py',
           'dsh/session/persistence.py',
           'dsh/session/persistence_jsonl_canonical.py',
           'dsh/session/persistence_sqlite_canonical.py',
           'dsh/session/preparations.py',
           'dsh/session/projections.py',
           'dsh/session/repair.py',
           'dsh/session/seq_ranges.py',
           'dsh/session/session_log_deepseek.py',
           'dsh/session/session_log_deepseek_invariant.py',
           'dsh/session/session_query.py',
           'dsh/session/sqlite_codec.py',
           'dsh/session/sqlite_compression.py',
           'dsh/session/sqlite_database.py',
           'dsh/session/sqlite_json.py',
           'dsh/session/sqlite_logical.py',
           'dsh/session/sqlite_schema.py',
           'dsh/session/sqlite_source_seqs.py',
           'dsh/session/sqlite_sql.py',
           'dsh/session/sqlite_store.py',
           'dsh/session/stats.py',
           'dsh/session/text.py',
           'dsh/session/title.py',
           'dsh/session/zstd.py',
           'dsh/settings/__init__.py',
           'dsh/settings/provider.py',
           'dsh/settings/redact.py',
           'dsh/settings/settings_file.py',
           'dsh/settings/types.py',
           'dsh/typert/__init__.py',
           'dsh/typert/protocol.py',
           'dsh/typert/registry.py',
           'dsh/typert/remote.py',
           'dsh/typert/stores.py'],
 'auxiliary': ['dsh/__init__.py',
               'dsh/compaction/__init__.py',
               'dsh/compaction/command_compact.py',
               'dsh/compaction/compaction_basic/__init__.py',
               'dsh/compaction/compaction_basic/config.py',
               'dsh/compaction/compaction_basic/region.py',
               'dsh/compaction/compaction_basic/summarizer.py',
               'dsh/compaction/engine.py',
               'dsh/compaction/native_summary.py',
               'dsh/compaction/pruner.py',
               'dsh/compaction/tool_pairing.py',
               'dsh/cordis/__init__.py',
               'dsh/cordis/awaiting.py',
               'dsh/cordis/context.py',
               'dsh/cordis/environment.py',
               'dsh/cordis/errors.py',
               'dsh/cordis/events.py',
               'dsh/cordis/fiber.py',
               'dsh/cordis/hmr.py',
               'dsh/cordis/include.py',
               'dsh/cordis/json_text.py',
               'dsh/cordis/loader.py',
               'dsh/cordis/logger.py',
               'dsh/cordis/plugin.py',
               'dsh/cordis/profile.py',
               'dsh/cordis/reflect.py',
               'dsh/cordis/registry.py',
               'dsh/cordis/schema.py',
               'dsh/cordis/service.py',
               'dsh/cordis/timer.py',
               'dsh/cordis/utils.py',
               'dsh/core/__init__.py',
               'dsh/core/abort.py',
               'dsh/core/agent.py',
               'dsh/core/agent_default_model_invariant.py',
               'dsh/core/agent_factory.py',
               'dsh/core/agent_loop.py',
               'dsh/core/agent_loop_settings.py',
               'dsh/core/cancellation.py',
               'dsh/core/configured_agents.py',
               'dsh/core/consumed_work.py',
               'dsh/core/inbox.py',
               'dsh/core/json_schema.py',
               'dsh/core/model_selection.py',
               'dsh/core/runtime_context.py',
               'dsh/core/scope.py',
               'dsh/core/session/__init__.py',
               'dsh/core/session/chunk_rows.py',
               'dsh/core/session/invariant.py',
               'dsh/core/session/json.py',
               'dsh/core/session/known_event_types.py',
               'dsh/core/session/preparation.py',
               'dsh/core/session/repair.py',
               'dsh/core/session/request_header.py',
               'dsh/core/session/seq_ranges.py',
               'dsh/core/session/session.py',
               'dsh/core/session/surface.py',
               'dsh/core/session/types.py',
               'dsh/core/surface.py',
               'dsh/core/tool_calls.py',
               'dsh/core/tools.py',
               'dsh/diagnostics/__init__.py',
               'dsh/diagnostics/invariants.py',
               'dsh/llm/adapter_failure.py',
               'dsh/llm/call_config.py',
               'dsh/llm/error.py',
               'dsh/llm/image_content.py',
               'dsh/llm/llm_service.py',
               'dsh/llm/model_info.py',
               'dsh/llm/message.py',
               'dsh/llm/stream_bridge.py',
               'dsh/session/__init__.py',
               'dsh/session/checkpoint_policy.py',
               'dsh/session/checkpoint_policy_invariant.py',
               'dsh/session/durable_publish.py',
               'dsh/session/file_io.py',
               'dsh/session/file_revision.py',
               'dsh/session/icu_collation.py',
               'dsh/session/jsonl_format.py',
               'dsh/session/jsonl_store.py',
               'dsh/session/jsonl_zstd.py',
               'dsh/session/persistence.py',
               'dsh/session/persistence_jsonl_canonical.py',
               'dsh/session/persistence_sqlite_canonical.py',
               'dsh/session/preparations.py',
               'dsh/session/projections.py',
               'dsh/session/repair.py',
               'dsh/session/seq_ranges.py',
               'dsh/session/session_log_deepseek.py',
               'dsh/session/session_log_deepseek_invariant.py',
               'dsh/session/session_query.py',
               'dsh/session/sqlite_codec.py',
               'dsh/session/sqlite_compression.py',
               'dsh/session/sqlite_database.py',
               'dsh/session/sqlite_json.py',
               'dsh/session/sqlite_logical.py',
               'dsh/session/sqlite_schema.py',
               'dsh/session/sqlite_source_seqs.py',
               'dsh/session/sqlite_sql.py',
               'dsh/session/sqlite_store.py',
               'dsh/session/stats.py',
               'dsh/session/text.py',
               'dsh/session/title.py',
               'dsh/session/zstd.py',
               'dsh/settings/__init__.py',
               'dsh/settings/provider.py',
               'dsh/settings/redact.py',
               'dsh/settings/settings_file.py',
               'dsh/settings/types.py',
               'dsh/typert/__init__.py',
               'dsh/typert/protocol.py',
               'dsh/typert/registry.py',
               'dsh/typert/remote.py',
               'dsh/typert/stores.py'],
 'failure': ['dsh/__init__.py',
             'dsh/cordis/__init__.py',
             'dsh/cordis/awaiting.py',
             'dsh/cordis/context.py',
             'dsh/cordis/environment.py',
             'dsh/cordis/errors.py',
             'dsh/cordis/events.py',
             'dsh/cordis/fiber.py',
             'dsh/cordis/hmr.py',
             'dsh/cordis/include.py',
             'dsh/cordis/json_text.py',
             'dsh/cordis/loader.py',
             'dsh/cordis/logger.py',
             'dsh/cordis/plugin.py',
             'dsh/cordis/profile.py',
             'dsh/cordis/reflect.py',
             'dsh/cordis/registry.py',
             'dsh/cordis/schema.py',
             'dsh/cordis/service.py',
             'dsh/cordis/timer.py',
             'dsh/cordis/utils.py',
             'dsh/core/__init__.py',
             'dsh/core/abort.py',
             'dsh/core/agent.py',
             'dsh/core/agent_default_model_invariant.py',
             'dsh/core/agent_factory.py',
             'dsh/core/agent_loop.py',
             'dsh/core/agent_loop_settings.py',
             'dsh/core/cancellation.py',
             'dsh/core/configured_agents.py',
             'dsh/core/consumed_work.py',
             'dsh/core/inbox.py',
             'dsh/core/json_schema.py',
             'dsh/core/model_selection.py',
             'dsh/core/runtime_context.py',
             'dsh/core/scope.py',
             'dsh/core/session/__init__.py',
             'dsh/core/session/chunk_rows.py',
             'dsh/core/session/invariant.py',
             'dsh/core/session/json.py',
             'dsh/core/session/known_event_types.py',
             'dsh/core/session/preparation.py',
             'dsh/core/session/repair.py',
             'dsh/core/session/request_header.py',
             'dsh/core/session/seq_ranges.py',
             'dsh/core/session/session.py',
             'dsh/core/session/surface.py',
             'dsh/core/session/types.py',
             'dsh/core/surface.py',
             'dsh/core/tool_calls.py',
             'dsh/core/tools.py',
             'dsh/diagnostics/__init__.py',
             'dsh/diagnostics/invariants.py',
             'dsh/llm/adapter_failure.py',
             'dsh/llm/call_config.py',
             'dsh/llm/error.py',
             'dsh/llm/llm_service.py',
             'dsh/llm/model_info.py',
             'dsh/llm/message.py',
             'dsh/llm/stream_bridge.py',
             'dsh/session/__init__.py',
             'dsh/session/checkpoint_policy.py',
             'dsh/session/checkpoint_policy_invariant.py',
             'dsh/session/durable_publish.py',
             'dsh/session/file_io.py',
             'dsh/session/file_revision.py',
             'dsh/session/icu_collation.py',
             'dsh/session/jsonl_format.py',
             'dsh/session/jsonl_store.py',
             'dsh/session/jsonl_zstd.py',
             'dsh/session/persistence.py',
             'dsh/session/persistence_jsonl_canonical.py',
             'dsh/session/persistence_sqlite_canonical.py',
             'dsh/session/preparations.py',
             'dsh/session/projections.py',
             'dsh/session/repair.py',
             'dsh/session/seq_ranges.py',
             'dsh/session/session_log_deepseek.py',
             'dsh/session/session_log_deepseek_invariant.py',
             'dsh/session/session_query.py',
             'dsh/session/sqlite_codec.py',
             'dsh/session/sqlite_compression.py',
             'dsh/session/sqlite_database.py',
             'dsh/session/sqlite_json.py',
             'dsh/session/sqlite_logical.py',
             'dsh/session/sqlite_schema.py',
             'dsh/session/sqlite_source_seqs.py',
             'dsh/session/sqlite_sql.py',
             'dsh/session/sqlite_store.py',
             'dsh/session/stats.py',
             'dsh/session/text.py',
             'dsh/session/title.py',
             'dsh/session/zstd.py',
             'dsh/settings/__init__.py',
             'dsh/settings/provider.py',
             'dsh/settings/redact.py',
             'dsh/settings/settings_file.py',
             'dsh/settings/types.py',
             'dsh/typert/__init__.py',
             'dsh/typert/protocol.py',
             'dsh/typert/registry.py',
             'dsh/typert/remote.py',
             'dsh/typert/stores.py'],
 'boundary': ['dsh/__init__.py',
              'dsh/cordis/__init__.py',
              'dsh/cordis/awaiting.py',
              'dsh/cordis/context.py',
              'dsh/cordis/environment.py',
              'dsh/cordis/errors.py',
              'dsh/cordis/events.py',
              'dsh/cordis/fiber.py',
              'dsh/cordis/hmr.py',
              'dsh/cordis/include.py',
              'dsh/cordis/json_text.py',
              'dsh/cordis/loader.py',
              'dsh/cordis/logger.py',
              'dsh/cordis/plugin.py',
              'dsh/cordis/profile.py',
              'dsh/cordis/reflect.py',
              'dsh/cordis/registry.py',
              'dsh/cordis/schema.py',
              'dsh/cordis/service.py',
              'dsh/cordis/timer.py',
              'dsh/cordis/utils.py',
              'dsh/core/__init__.py',
              'dsh/core/abort.py',
              'dsh/core/agent.py',
              'dsh/core/agent_default_model_invariant.py',
              'dsh/core/agent_factory.py',
              'dsh/core/agent_loop.py',
              'dsh/core/agent_loop_settings.py',
              'dsh/core/cancellation.py',
              'dsh/core/configured_agents.py',
              'dsh/core/consumed_work.py',
              'dsh/core/inbox.py',
              'dsh/core/json_schema.py',
              'dsh/core/model_selection.py',
              'dsh/core/runtime_context.py',
              'dsh/core/scope.py',
              'dsh/core/session/__init__.py',
              'dsh/core/session/chunk_rows.py',
              'dsh/core/session/invariant.py',
              'dsh/core/session/json.py',
              'dsh/core/session/known_event_types.py',
              'dsh/core/session/preparation.py',
              'dsh/core/session/repair.py',
              'dsh/core/session/request_header.py',
              'dsh/core/session/seq_ranges.py',
              'dsh/core/session/session.py',
              'dsh/core/session/surface.py',
              'dsh/core/session/types.py',
              'dsh/core/surface.py',
              'dsh/core/tool_calls.py',
              'dsh/core/tools.py',
              'dsh/diagnostics/__init__.py',
              'dsh/diagnostics/invariants.py',
              'dsh/llm/adapter_failure.py',
              'dsh/llm/call_config.py',
              'dsh/llm/error.py',
              'dsh/llm/image_content.py',
              'dsh/llm/llm_service.py',
              'dsh/llm/model_info.py',
              'dsh/llm/message.py',
              'dsh/llm/stream_bridge.py',
              'dsh/session/__init__.py',
              'dsh/session/checkpoint_policy.py',
              'dsh/session/checkpoint_policy_invariant.py',
              'dsh/session/durable_publish.py',
              'dsh/session/file_io.py',
              'dsh/session/file_revision.py',
              'dsh/session/icu_collation.py',
              'dsh/session/jsonl_format.py',
              'dsh/session/jsonl_store.py',
              'dsh/session/jsonl_zstd.py',
              'dsh/session/persistence.py',
              'dsh/session/persistence_jsonl_canonical.py',
              'dsh/session/persistence_sqlite_canonical.py',
              'dsh/session/preparations.py',
              'dsh/session/projections.py',
              'dsh/session/repair.py',
              'dsh/session/seq_ranges.py',
              'dsh/session/session_log_deepseek.py',
              'dsh/session/session_log_deepseek_invariant.py',
              'dsh/session/session_query.py',
              'dsh/session/sqlite_codec.py',
              'dsh/session/sqlite_compression.py',
              'dsh/session/sqlite_database.py',
              'dsh/session/sqlite_json.py',
              'dsh/session/sqlite_logical.py',
              'dsh/session/sqlite_schema.py',
              'dsh/session/sqlite_source_seqs.py',
              'dsh/session/sqlite_sql.py',
              'dsh/session/sqlite_store.py',
              'dsh/session/stats.py',
              'dsh/session/text.py',
              'dsh/session/title.py',
              'dsh/session/zstd.py',
              'dsh/settings/__init__.py',
              'dsh/settings/provider.py',
              'dsh/settings/redact.py',
              'dsh/settings/settings_file.py',
              'dsh/settings/types.py',
              'dsh/typert/__init__.py',
              'dsh/typert/protocol.py',
              'dsh/typert/registry.py',
              'dsh/typert/remote.py',
              'dsh/typert/stores.py'],
 'iterator': ['dsh/__init__.py',
              'dsh/cordis/__init__.py',
              'dsh/cordis/awaiting.py',
              'dsh/cordis/context.py',
              'dsh/cordis/environment.py',
              'dsh/cordis/errors.py',
              'dsh/cordis/events.py',
              'dsh/cordis/fiber.py',
              'dsh/cordis/hmr.py',
              'dsh/cordis/include.py',
              'dsh/cordis/json_text.py',
              'dsh/cordis/loader.py',
              'dsh/cordis/logger.py',
              'dsh/cordis/plugin.py',
              'dsh/cordis/profile.py',
              'dsh/cordis/reflect.py',
              'dsh/cordis/registry.py',
              'dsh/cordis/schema.py',
              'dsh/cordis/service.py',
              'dsh/cordis/timer.py',
              'dsh/cordis/utils.py',
              'dsh/core/__init__.py',
              'dsh/core/abort.py',
              'dsh/core/agent.py',
              'dsh/core/agent_default_model_invariant.py',
              'dsh/core/agent_factory.py',
              'dsh/core/agent_loop.py',
              'dsh/core/agent_loop_settings.py',
              'dsh/core/cancellation.py',
              'dsh/core/configured_agents.py',
              'dsh/core/consumed_work.py',
              'dsh/core/inbox.py',
              'dsh/core/json_schema.py',
              'dsh/core/model_selection.py',
              'dsh/core/runtime_context.py',
              'dsh/core/scope.py',
              'dsh/core/session/__init__.py',
              'dsh/core/session/chunk_rows.py',
              'dsh/core/session/invariant.py',
              'dsh/core/session/json.py',
              'dsh/core/session/known_event_types.py',
              'dsh/core/session/preparation.py',
              'dsh/core/session/repair.py',
              'dsh/core/session/request_header.py',
              'dsh/core/session/seq_ranges.py',
              'dsh/core/session/session.py',
              'dsh/core/session/surface.py',
              'dsh/core/session/types.py',
              'dsh/core/surface.py',
              'dsh/core/tool_calls.py',
              'dsh/core/tools.py',
              'dsh/diagnostics/__init__.py',
              'dsh/diagnostics/invariants.py',
              'dsh/llm/adapter_failure.py',
              'dsh/llm/call_config.py',
              'dsh/llm/error.py',
              'dsh/llm/llm_service.py',
              'dsh/llm/model_info.py',
              'dsh/llm/message.py',
              'dsh/llm/stream_bridge.py',
              'dsh/session/__init__.py',
              'dsh/session/checkpoint_policy.py',
              'dsh/session/checkpoint_policy_invariant.py',
              'dsh/session/durable_publish.py',
              'dsh/session/file_io.py',
              'dsh/session/file_revision.py',
              'dsh/session/icu_collation.py',
              'dsh/session/jsonl_format.py',
              'dsh/session/jsonl_store.py',
              'dsh/session/jsonl_zstd.py',
              'dsh/session/persistence.py',
              'dsh/session/persistence_jsonl_canonical.py',
              'dsh/session/persistence_sqlite_canonical.py',
              'dsh/session/preparations.py',
              'dsh/session/projections.py',
              'dsh/session/repair.py',
              'dsh/session/seq_ranges.py',
              'dsh/session/session_log_deepseek.py',
              'dsh/session/session_log_deepseek_invariant.py',
              'dsh/session/session_query.py',
              'dsh/session/sqlite_codec.py',
              'dsh/session/sqlite_compression.py',
              'dsh/session/sqlite_database.py',
              'dsh/session/sqlite_json.py',
              'dsh/session/sqlite_logical.py',
              'dsh/session/sqlite_schema.py',
              'dsh/session/sqlite_source_seqs.py',
              'dsh/session/sqlite_sql.py',
              'dsh/session/sqlite_store.py',
              'dsh/session/stats.py',
              'dsh/session/text.py',
              'dsh/session/title.py',
              'dsh/session/zstd.py',
              'dsh/settings/__init__.py',
              'dsh/settings/provider.py',
              'dsh/settings/redact.py',
              'dsh/settings/settings_file.py',
              'dsh/settings/types.py',
              'dsh/typert/__init__.py',
              'dsh/typert/protocol.py',
              'dsh/typert/registry.py',
              'dsh/typert/remote.py',
              'dsh/typert/stores.py']}
FIXTURE_PATH = 'scripts/oracles/canonical-llm-fixtures.json'
NAMES_BY_GROUP = json.loads((ROOT / FIXTURE_PATH).read_text(encoding='utf-8'))
NAMES = tuple(group + '/' + name for group in GROUPS for name in NAMES_BY_GROUP[group])
SOURCE_INPUTS = {
    'migration/modules.json',
    'reference/packages/compaction/compaction-basic/src/config.ts',
    'reference/packages/compaction/compaction-basic/src/index.ts',
    'reference/packages/compaction/compaction-basic/src/invariant.ts',
    'reference/packages/compaction/compaction-basic/src/region.ts',
    'reference/packages/compaction/compaction-basic/src/summarizer.ts',
    'reference/packages/compaction/compaction-basic/src/types.ts',
    'reference/packages/core/agent-loop/src/agent.ts',
    'reference/packages/core/agent-loop/src/constants.ts',
    'reference/packages/core/agent-loop/src/index.ts',
    'reference/packages/core/agent-loop/src/invariant.ts',
    'reference/packages/core/agent-loop/src/runtime-context.ts',
    'reference/packages/core/agent-loop/src/tool-calls.ts',
    'reference/packages/llm/llm-deepseek/src/adapter.ts',
    'reference/packages/llm/llm-deepseek/src/file-id.ts',
    'reference/packages/llm/llm-deepseek/src/file-store.ts',
    'reference/packages/llm/llm-deepseek/src/files-api.ts',
    'reference/packages/llm/llm-deepseek/src/image-tokens.ts',
    'reference/packages/llm/llm-deepseek/src/index.ts',
    'reference/packages/llm/llm-deepseek/src/invariant.ts',
    'reference/packages/llm/llm-deepseek/src/request-pricing.ts',
    'reference/packages/llm/llm-deepseek/src/serialize.ts',
    'reference/packages/llm/llm-deepseek/src/sse.ts',
    'reference/packages/llm/llm-deepseek/src/translate.ts',
    'reference/packages/llm/llm-deepseek/src/types.ts',
    'reference/packages/llm/llm-deepseek/src/upload-index.ts',
    'reference/packages/llm/llm-retry/src/brand.ts',
    'reference/packages/llm/llm-retry/src/history.ts',
    'reference/packages/llm/llm-retry/src/index.ts',
    'reference/packages/llm/llm-retry/src/invariant.ts',
    'reference/packages/llm/llm-retry/src/types.ts',
    'reference/packages/llm/llm/src/adapter-failure.ts',
    'reference/packages/llm/llm/src/api-key.ts',
    'reference/packages/llm/llm/src/assembler.ts',
    'reference/packages/llm/llm/src/attribution.ts',
    'reference/packages/llm/llm/src/brand.ts',
    'reference/packages/llm/llm/src/call-config.ts',
    'reference/packages/llm/llm/src/content.ts',
    'reference/packages/llm/llm/src/error.ts',
    'reference/packages/llm/llm/src/index.ts',
    'reference/packages/llm/llm/src/invariant.ts',
    'reference/packages/llm/llm/src/message.ts',
    'reference/packages/llm/llm/src/never.ts',
    'reference/packages/llm/llm/src/retry-policy.ts',
    'reference/packages/llm/llm/src/types.ts',
    'scripts/canonical_llm_oracle.py',
    'scripts/import_paths.py',
    'scripts/canonical_llm_values.py',
    'scripts/oracles/canonical-llm-fixtures.json',
    'scripts/oracles/canonical_llm_auxiliary.probe.spec.ts',
    'scripts/oracles/canonical_llm_auxiliary_python.py',
    'scripts/oracles/canonical_llm_boundary.probe.spec.ts',
    'scripts/oracles/canonical_llm_boundary_python.py',
    'scripts/oracles/canonical_llm_failure.probe.spec.ts',
    'scripts/oracles/canonical_llm_failure_python.py',
    'scripts/oracles/canonical_llm_iterator.probe.spec.ts',
    'scripts/oracles/canonical_llm_iterator_python.py',
    'scripts/oracles/canonical_llm_python.py',
    'scripts/oracles/canonical_llm_retry.probe.spec.ts',
    'scripts/oracles/canonical_llm_retry_python.py',
    'scripts/oracles/vitest.agent-lifecycle.config.mts',
    'scripts/oracles/vitest.canonical-llm-probe.config.mts',
    'scripts/oracles/vitest.consumers.config.mts',
    'scripts/oracles/vitest.core.config.mts',
    'scripts/oracles/vitest.deepseek-probe.config.mts',
}
REQUIRED_MODULES = {'dsh/llm/llm_service.py', 'dsh/llm/adapter_failure.py',
    'dsh/core/agent_loop.py', 'dsh/compaction/native_summary.py', 'dsh/cordis/context.py',
    'dsh/llm/llm_deepseek.py', 'dsh/llm/llm_retry.py', 'dsh/core/session/session.py'}


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def observation_digest(rows, side='native'):
    if not isinstance(rows, list) or len(rows) != len(NAMES) or any(not isinstance(row, dict) for row in rows) or tuple(row.get('name') for row in rows) != NAMES:
        raise ValueError('Canonical LLM observations missing, duplicate or reordered')
    if any(row.get('group') != row['name'].split('/')[0] for row in rows):
        raise ValueError('Canonical LLM observation group differs')
    return value_digest(rows, side=side)


def identity(source, check_files=True):
    if not isinstance(source, dict) or source.get('sourceCommit') != SOURCE_COMMIT or source.get('node') != 'v22.22.2':
        raise ValueError('Canonical LLM Source identity differs')
    if not isinstance(source.get('inputs'), dict) or set(source['inputs']) != SOURCE_INPUTS:
        raise ValueError('Canonical LLM Source guard inputs differ')
    if check_files and source['inputs'] != {name: digest(ROOT / name) for name in SOURCE_INPUTS}:
        raise ValueError('Canonical LLM Source guard bytes differ')
    return observation_digest(source['rows'], side='source')


def validate_modules(modules, root, check_files):
    if not isinstance(modules, dict) or not modules:
        raise ValueError('Canonical LLM imported modules missing')
    missing_prefixes = None if check_files else {}
    for name, expected in modules.items():
        if not isinstance(name, str) or not name.startswith('dsh/') or '..' in Path(name).parts or ':' in name or '\\' in name:
            raise ValueError('Canonical LLM imported path invalid')
        selected = resolve_import_path(root, name, missing_prefixes)
        if selected.relative_to(root).as_posix() != name or not isinstance(expected, str) or len(expected) != 64 or any(character not in '0123456789abcdef' for character in expected):
            raise ValueError('Canonical LLM imported identity invalid')
        if check_files and digest(selected) != expected:
            raise ValueError('Canonical LLM actual imported bytes differ')


def validate_runtime(report, root, expected_digest, modules, check_files=True):
    root = Path(root).resolve()
    if not isinstance(report, dict) or Path(report['root']).resolve() != root or not report['python'].startswith('3.8.10 '):
        raise ValueError('Canonical LLM selected root or Python differs')
    validate_executable(report['executable'], root, check_files)
    if not isinstance(modules, dict) or report.get('modules') != modules or not REQUIRED_MODULES.issubset(modules):
        raise ValueError('Canonical LLM imported module closure differs')
    validate_modules(modules, root, check_files)
    groups = report.get('groups')
    if not isinstance(groups, dict) or set(groups) != set(GROUPS):
        raise ValueError('Canonical LLM child reports missing')
    child_rows, child_modules = [], {}
    for group in GROUPS:
        child = groups[group]
        if not isinstance(child, dict) or Path(child['root']).resolve() != root or child['python'] != report['python'] or child['executable'] != report['executable']:
            raise ValueError('Canonical LLM child runtime differs')
        if not isinstance(child.get('rows'), list) or tuple(row.get('name') for row in child['rows'] if isinstance(row, dict)) != tuple(NAMES_BY_GROUP[group]):
            raise ValueError('Canonical LLM child rows incomplete')
        if set(child.get('modules', {})) != set(GROUP_MODULES[group]):
            raise ValueError('Canonical LLM child imported module closure differs')
        validate_modules(child['modules'], root, check_files)
        for name, expected in child['modules'].items():
            if name in child_modules and child_modules[name] != expected:
                raise ValueError('Canonical LLM child module ownership differs')
            child_modules[name] = expected
        child_rows.extend(dict(row, group=group, name=group + '/' + row['name']) for row in child['rows'])
    if child_modules != modules or child_rows != report['rows']:
        raise ValueError('Canonical LLM child and aggregate receipts differ')
    if observation_digest(report['rows']) != expected_digest:
        raise ValueError('Canonical LLM complete observed values differ')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', type=Path, required=True)
    options = parser.parse_args()
    output = options.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    source_path, native_path = output.with_suffix('.source.json'), output.with_suffix('.native.json')
    child_sources = {group: output.with_suffix('.' + group + '.source.json') for group in GROUPS}
    if any(path.exists() for path in (output, source_path, native_path, *child_sources.values())):
        raise ValueError('Fresh canonical LLM outputs required')
    report = dict(status='runner-error')
    try:
        source_pin()
        inputs = {name: digest(ROOT / name) for name in SOURCE_INPUTS}
        environment = dict(os.environ)
        environment.update({'DSH_CANONICAL_LLM_' + group.upper() + '_OUTPUT': str(path) for group, path in child_sources.items()})
        with output.with_suffix('.source.log').open('xb') as stream:
            completed = subprocess.run(['node', 'scripts/oracles/official/node_modules/vitest/vitest.mjs',
                'run', '--config', 'scripts/oracles/vitest.canonical-llm-probe.config.mts'],
                cwd=str(ROOT), env=environment, stdout=stream, stderr=subprocess.STDOUT, timeout=240)
        if completed.returncode:
            raise RuntimeError('Actual canonical LLM Source observers failed')
        rows = []
        for group, path in child_sources.items():
            child = json.loads(path.read_text(encoding='utf-8'))
            if child['sourceCommit'] != SOURCE_COMMIT or child['node'] != 'v22.22.2' or [row['name'] for row in child['rows']] != NAMES_BY_GROUP[group]:
                raise ValueError('Actual canonical LLM Source child identity or rows differ')
            rows.extend(dict(row, group=group, name=group + '/' + row['name']) for row in child['rows'])
        source = dict(sourceCommit=SOURCE_COMMIT, node='v22.22.2', inputs=inputs, rows=rows)
        with source_path.open('x', encoding='utf-8') as stream:
            json.dump(source, stream, indent=2)
            stream.write('\n')
        expected = identity(source)
        with output.with_suffix('.native.log').open('xb') as stream:
            completed = subprocess.run([sys.executable, '-I', 'scripts/oracles/canonical_llm_python.py',
                '--root', str(ROOT), '--output', str(native_path)], cwd=str(ROOT), stdout=stream,
                stderr=subprocess.STDOUT, timeout=300)
        if completed.returncode:
            raise RuntimeError('Actual canonical LLM native observers failed')
        native = json.loads(native_path.read_text(encoding='utf-8'))
        modules = {name: digest(ROOT / name) for name in native['modules']}
        validate_runtime(native, ROOT, expected, modules)
        source_pin()
        identity(source)
        report.update(status='matched', target_upstream=SOURCE_COMMIT, cases=len(NAMES),
            observations_sha256=expected, modules=modules,
            scope='81 selected complete actual canonical retry, public failure/preparation/projection, auxiliary summary and SDK iterator ownership captures. Correlated typed generated message/retry identities and same-valued JSON numeric spelling only. Stable tool identifiers and every captured literal/error/request/event remain exact. Sequence/time, uncaptured HTTP headers, arbitrary graph ABI and all-profile journeys remain open.')
    except Exception as error:
        report['error'] = str(error)
        raise
    finally:
        with output.open('x', encoding='utf-8') as stream:
            json.dump(report, stream, indent=2)
            stream.write('\n')


if __name__ == '__main__':
    main()
